In [1]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import sklearn.preprocessing as pre 
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import mutual_info_classif, SelectKBest
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm
import statsmodels.tools as tools

In [2]:
import os
os.getcwd()

'C:\\Users\\USER'

In [3]:
os.chdir('C:\\Users\\USER\\Documents\\python_works')

In [8]:
data = pd.read_csv('Iris.csv')
data = data.set_index('Id')

In [9]:
data

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                           
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [11]:
data.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [12]:
data.Species = data.Species.replace({'Iris-setosa' : 1, 'Iris-versicolor' : 2, 'Iris-virginica' : 3})

In [13]:
data

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
Id                                                                    
1              5.1           3.5            1.4           0.2        1
2              4.9           3.0            1.4           0.2        1
3              4.7           3.2            1.3           0.2        1
4              4.6           3.1            1.5           0.2        1
5              5.0           3.6            1.4           0.2        1
..             ...           ...            ...           ...      ...
146            6.7           3.0            5.2           2.3        3
147            6.3           2.5            5.0           1.9        3
148            6.5           3.0            5.2           2.0        3
149            6.2           3.4            5.4           2.3        3
150            5.9           3.0            5.1           1.8        3

[150 rows x 5 columns]

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 7.0 KB


In [16]:
x = data.drop('Species', axis =1)
y = data.Species

In [17]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 25, stratify =y)

In [18]:
model = LogisticRegression()

In [19]:
mymodel = model.fit(X_train, y_train)

In [20]:
mymodel.intercept_

array([ 10.29233343,   1.87656637, -12.16889981])

In [21]:
mymodel.coef_

array([[-0.48520403,  0.7534145 , -2.37213312, -0.99123064],
       [ 0.53503453, -0.32094273, -0.12474194, -1.0566144 ],
       [-0.0498305 , -0.43247176,  2.49687506,  2.04784504]])

In [27]:
y_pred = mymodel.predict(X_test)
y_pred

array([3, 3, 3, 2, 1, 2, 2, 2, 1, 2, 3, 3, 1, 1, 1, 1, 1, 2, 1, 3, 1, 3,
       2, 2, 2, 3, 1, 3, 2, 2], dtype=int64)

In [29]:
confusion_matrix(y_test, y_pred)

array([[10,  0,  0],
       [ 0,  9,  1],
       [ 0,  2,  8]], dtype=int64)

In [30]:
accuracy_score(y_test, y_pred)

0.9

In [24]:
x= sm.add_constant(x)

In [25]:
x

const  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Id                                                                  
1      1.0            5.1           3.5            1.4           0.2
2      1.0            4.9           3.0            1.4           0.2
3      1.0            4.7           3.2            1.3           0.2
4      1.0            4.6           3.1            1.5           0.2
5      1.0            5.0           3.6            1.4           0.2
..     ...            ...           ...            ...           ...
146    1.0            6.7           3.0            5.2           2.3
147    1.0            6.3           2.5            5.0           1.9
148    1.0            6.5           3.0            5.2           2.0
149    1.0            6.2           3.4            5.4           2.3
150    1.0            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [36]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 25, stratify =y)

In [37]:
lreg = sm.Logit(y_train, X_train).fit()

ValueError: endog must be in the unit interval.